// 0.4: Systems & Hardware Assessment
// Pure assessment — no info steps

export const systemsAssessment = {
  id: "0.4-assess",
  sectionId: "0.4",
  title: "Assessment: Systems & Hardware for ML",
  difficulty: "easy",
  estimatedMinutes: 12,
  moduleType: "test",
  steps: [
    {
      type: "mc",
      question: "An NVIDIA GPU organizes execution into Streaming Multiprocessors (SMs), each running multiple warps. What is a warp, and why does warp-level execution matter for ML kernel performance?",
      options: ["A warp is a group of 32 threads that execute the same instruction simultaneously (SIMT — Single Instruction, Multiple Threads). If threads within a warp take different branches (warp divergence), both paths are executed serially with threads masked, reducing throughput. For ML kernels, data-parallel operations (like elementwise ops) naturally avoid divergence, while operations with data-dependent branching can suffer significant slowdowns", "A warp is a group of 64 threads that share an instruction cache and execute instructions in a round-robin fashion. Warps are purely a software abstraction with no hardware-level significance — the GPU scheduler treats individual threads as the fundamental unit of execution", "A warp is a dedicated hardware unit within each SM that performs matrix multiplication using tensor cores. Each SM contains multiple warps, and they operate in parallel to tile large matrix operations across the available tensor core compute units", "A warp is a memory controller that manages 32 consecutive bytes in HBM, coalescing memory requests from threads into aligned transactions. Each SM has multiple warp controllers that pipeline memory accesses to hide latency through transaction-level parallelism"],
      correct: 0,
      explanation: "The warp is the fundamental unit of execution on NVIDIA GPUs. All 32 threads in a warp share a program counter and execute in lockstep. When an `if` statement causes some threads to take one branch and others a different branch, the hardware serializes: it executes the `if` path (masking threads that took `else`), then the `else` path (masking the others). For ML, this means kernels should minimize data-dependent branching. Quantization kernels that branch on per-element conditions can suffer severe warp divergence. Structured operations (matmul, reductions, elementwise) naturally keep warps coherent."
    },
    {
      type: "mc",
      question: "PyTorch's autograd system records operations on tensors with `requires_grad=True` to enable automatic differentiation. How does it work internally?",
      options: [
        "PyTorch uses symbolic differentiation: it statically analyzes the Python source code using AST parsing to produce a closed-form derivative function before any tensor computation occurs, similar to how Mathematica or SymPy compute derivatives. This pre-computed derivative function is then compiled and called during the backward pass",
        "PyTorch builds a dynamic computational graph (the autograd tape) during the forward pass: each operation records a `grad_fn` node containing the backward function and references to input tensors. Calling `.backward()` traverses this graph in reverse topological order, applying the chain rule. The graph is destroyed after each backward pass (unless `retain_graph=True`), allowing Python control flow to change the graph each iteration",
        "PyTorch uses numerical differentiation (finite differences) to estimate gradients: for each parameter $\\theta_i$, it computes $(\\mathcal{L}(\\theta_i + h) - \\mathcal{L}(\\theta_i - h)) / 2h$ with a small perturbation $h$. This requires $2d$ forward passes for $d$ parameters but avoids the need to implement any backward functions",
        "PyTorch precompiles all possible computation graphs at import time by tracing every code path through the model definition, then selects the correct pre-compiled graph at runtime based on the input tensor shapes and dtypes, caching the selected graph for reuse across iterations with matching input signatures"
      ],
      correct: 1,
      explanation: "PyTorch's define-by-run paradigm builds the graph dynamically. For `y = torch.relu(x @ W + b)`, the forward pass creates nodes: MatmulBackward -> AddBackward -> ReluBackward, each storing the information needed for the backward pass (e.g., MatmulBackward stores $x$ and $W$ for computing $\\partial L/\\partial W = x^\\top \\partial L/\\partial y$ and $\\partial L/\\partial x = \\partial L/\\partial y \\cdot W^\\top$). This dynamic graph naturally handles Python `if` statements, loops, and recursion — the graph simply reflects whatever operations were executed. The cost is per-operation overhead, which `torch.compile` mitigates."
    },
    {
      type: "mc",
      question: "`torch.compile` transforms PyTorch code for faster execution. What does it actually do under the hood?",
      options: ["It converts the PyTorch model definition to C++ source code and compiles it with GCC, bypassing the Python interpreter entirely to eliminate per-operation overhead and producing a standalone executable that runs the model's forward and backward passes natively", "It replaces all PyTorch operations with pre-optimized cuDNN library calls by matching each operator to the closest cuDNN primitive, leveraging NVIDIA's hand-tuned implementations to achieve peak throughput without requiring any changes to the model code or graph structure", "It enables CUDA graphs for all operations without performing any graph transformation or operator fusion, simply recording the sequence of kernel launches and replaying them to eliminate per-launch CPU overhead while keeping each kernel identical to the eager-mode version", "It uses TorchDynamo to capture the computational graph by intercepting Python bytecode, then passes the graph to a backend compiler (TorchInductor by default) that performs operator fusion, memory planning, and generates optimized Triton kernels or CUDA code. Graph breaks occur when unsupported Python constructs are encountered"],
      correct: 3,
      explanation: "The `torch.compile` pipeline has three stages: (1) TorchDynamo modifies CPython's frame evaluation to trace through Python bytecode, capturing the computation as an FX graph while handling Python control flow via guards and graph breaks. (2) AOTAutograd traces the forward and backward passes ahead-of-time, enabling joint optimization. (3) TorchInductor (the default backend) applies optimizations like operator fusion (combining pointwise ops into single kernels), memory planning (reusing buffers), and code generation (emitting optimized Triton kernels). The result is significantly fewer, larger kernel launches."
    },
    {
      type: "mc",
      question: "In data-parallel distributed training, all-reduce is the standard collective communication operation for synchronizing gradients. What does all-reduce compute, and what is the bandwidth cost of the ring all-reduce algorithm?",
      options: ["All-reduce sends all gradients to a designated central server node, which computes the element-wise mean and broadcasts the result back to all workers. The total communication cost is $O(N \\cdot M)$ where $N$ is the number of workers and $M$ is the message size, making the approach increasingly expensive as the cluster size grows and creating a single bandwidth bottleneck at the server", "All-reduce randomly selects one worker's gradient tensor at each synchronization step and copies it to all other workers via broadcast, providing an unbiased stochastic estimate of the true gradient mean while requiring only $M$ bytes of communication per step regardless of the number of workers $N$, at the cost of increased gradient variance proportional to $N$", "All-reduce computes the sum (or mean) of tensors across all $N$ workers and places the result on every worker. Ring all-reduce achieves this in $2(N-1)/N \\cdot M$ bytes of data transferred per worker (asymptotically $2M$), which is independent of $N$ — making it bandwidth-optimal. It proceeds in two phases: reduce-scatter and all-gather, each taking $N-1$ steps", "All-reduce only works with exactly 2 workers at a time and must be composed recursively via a binary tree structure for larger clusters, resulting in $O(M \\log N)$ total communication per worker and $O(\\log N)$ synchronization rounds, which is suboptimal compared to direct multi-worker ring algorithms but has lower latency per step due to the tree's shorter critical path"],
      correct: 2,
      explanation: "Ring all-reduce arranges $N$ workers in a logical ring. Phase 1 (reduce-scatter): over $N-1$ steps, each worker sends a $1/N$-th chunk of its data to the next worker while receiving and accumulating a chunk from the previous worker. After $N-1$ steps, each worker holds the fully reduced version of one chunk. Phase 2 (all-gather): over $N-1$ steps, these reduced chunks are circulated so every worker gets all chunks. Total data per worker: $(N-1)/N \\cdot M$ per phase, or $2(N-1)/N \\cdot M$ total. This is bandwidth-optimal: the lower bound is $2(N-1)/N \\cdot M$. The latency is $O(N)$ steps, which tree-based algorithms reduce to $O(\\log N)$."
    },
    {
      type: "mc",
      question: "A parameter server architecture is an alternative to all-reduce for distributed training. How does it differ, and when is each approach preferred?",
      options: ["In a parameter server architecture, dedicated server nodes store model parameters, and worker nodes push gradients and pull updated weights. This enables asynchronous SGD (workers don't wait for each other) but introduces stale gradients. All-reduce is synchronous and bandwidth-optimal for dense gradients. Parameter servers are preferred for sparse models (e.g., recommendation models with large embedding tables) where each worker only accesses a subset of parameters", "Parameter servers are always faster than all-reduce because asynchronous gradient updates eliminate synchronization barriers entirely, and the server nodes provide dedicated compute for the optimizer step that would otherwise compete with forward/backward computation on the worker GPUs. This architectural separation of concerns means parameter servers strictly dominate all-reduce in throughput for any model size and any cluster configuration", "Parameter servers and all-reduce are mathematically identical algorithms that always produce the same model updates given the same data and the same random seed, differing only in their implementation topology — the parameter server uses a star topology while all-reduce uses a ring topology for routing the same communication volume. The choice between them is purely an engineering decision based on available network hardware", "Parameter servers operate exclusively on CPU memory to store and update parameters, while all-reduce operates exclusively on GPU memory for gradient aggregation — the two approaches target different hardware tiers in the memory hierarchy and cannot be combined within a single training framework, because their memory management strategies are fundamentally incompatible at the driver level"],
      correct: 0,
      explanation: "Parameter servers split the model across server nodes. Workers compute gradients on their data, push gradients to servers, and pull updated parameters. This naturally handles sparse updates: if a worker only touches embedding rows $\\{5, 1000, 50000\\}$, it only communicates those rows, not the entire embedding table. Asynchronous PS allows workers to proceed without synchronization barriers, improving throughput but introducing gradient staleness that can hurt convergence. For dense transformer training, synchronous all-reduce is preferred because all parameters are updated every step and ring all-reduce is bandwidth-optimal for this pattern."
    },
    {
      type: "mc",
      question: "NVLink and NVSwitch provide high-bandwidth GPU-to-GPU interconnects within a node, while InfiniBand connects nodes across a cluster. What are the typical bandwidth differences, and why does this matter for model parallelism?",
      options: [
        "NVLink and InfiniBand provide the same effective bandwidth (~25 GB/s bidirectional) but differ in protocol overhead, so the choice between them is purely a matter of cost and availability rather than any performance-driven constraint on where to place different parallelism strategies within the cluster topology",
        "NVLink (4th gen, A100/H100) provides 600-900 GB/s bidirectional bandwidth between GPUs, while InfiniBand HDR provides ~25 GB/s per port (200 Gbps). NVSwitch enables all-to-all NVLink connectivity within a node. This ~30x bandwidth gap means tensor parallelism (which requires high-bandwidth all-reduce every layer) should be confined within NVLink-connected GPUs, while pipeline and data parallelism (less frequent communication) span across nodes via InfiniBand",
        "InfiniBand is faster than NVLink in raw bandwidth but has significantly higher latency per message due to the network fabric traversal, making it better suited for large bulk transfers while NVLink excels at the many small messages typical of tensor parallelism's frequent synchronization points",
        "NVLink connects GPUs to CPUs (not GPUs to other GPUs), providing a high-bandwidth path for CPU-GPU data movement that accelerates host-to-device transfers. GPU-to-GPU communication within a node uses PCIe peer-to-peer transfers, while InfiniBand handles all inter-node GPU communication"
      ],
      correct: 1,
      explanation: "In an 8-GPU DGX A100 node with NVSwitch, any GPU can communicate with any other at 600 GB/s. Across nodes, InfiniBand HDR gives ~25 GB/s per link (often 4-8 links per node for 100-200 GB/s aggregate). Tensor parallelism splits individual matrix multiplications across GPUs, requiring an all-reduce of the full hidden dimension after every layer — this demands the highest bandwidth and must use NVLink. Pipeline parallelism only communicates activations between pipeline stages (much less data), suitable for the slower InfiniBand. This creates a hierarchical parallelism strategy: TP within a node, PP across nodes, DP across replicas."
    },
    {
      type: "mc",
      question: "When profiling a training run with PyTorch Profiler, you see that a single linear layer (`nn.Linear(4096, 4096)`) takes 0.5ms with batch size 1 but only 0.6ms with batch size 64. What explains this sublinear scaling of time with batch size?",
      options: ["PyTorch automatically reduces the numerical precision from FP16 to INT8 for larger batches to maintain throughput, trading a small amount of accuracy for a 2x reduction in memory bandwidth requirements per element, which keeps the wall-clock time nearly constant as batch size grows", "Batch size 64 triggers cuBLAS to select a fundamentally different CUDA kernel implementation that uses a Strassen-like algorithm with $O(n^{2.81})$ complexity instead of the standard $O(n^3)$ algorithm, yielding a multiplicative speedup that is independent of the memory subsystem", "The GPU dynamically overclocks its compute units when it detects larger batch sizes via a hardware-level occupancy monitor, boosting the clock frequency by up to 30% when the workload is large enough to thermally justify the increased power consumption without risking thermal throttling", "With batch size 1, the matmul is $y = Wx$ where $W \\in \\mathbb{R}^{4096 \\times 4096}$ and $x \\in \\mathbb{R}^{4096}$: 33M FLOPs but 32MB of weight data to load — arithmetic intensity of ~1 FLOP/byte (memory-bound). With batch size 64, $X \\in \\mathbb{R}^{64 \\times 4096}$: 2.1B FLOPs but the same 32MB of weights — arithmetic intensity of ~64 FLOP/byte (compute-bound). The weights are loaded once and reused across all batch elements, so increasing batch size is nearly free until compute saturation"],
      correct: 3,
      explanation: "This is the classic memory-bound to compute-bound transition. For $y = WX^\\top$ with $W \\in \\mathbb{R}^{m \\times k}$, $X \\in \\mathbb{R}^{B \\times k}$: FLOPs $= 2mBk$, bytes $\\approx (mk + Bk) \\times 2$ (FP16). Arithmetic intensity $I \\approx 2mB/(m+B)$ FLOP/byte. For $m = k = 4096$: $B = 1$ gives $I \\approx 2$, $B = 64$ gives $I \\approx 124$, and $B = 256$ gives $I \\approx 470$. On an A100 (ridge point ~156), $B = 64$ is still somewhat memory-bound but much closer to compute-bound, while $B = 256$ is fully compute-bound. This is why batching is critical for inference throughput."
    },
    {
      type: "mc",
      question: "NVIDIA Nsight Systems and Nsight Compute are two profiling tools. What is the key difference between them, and when would you use each?",
      options: ["They are identical tools with different names for different GPU architectures — Nsight Systems targets Ampere and older GPUs while Nsight Compute targets Hopper and newer architectures, with each version including architecture-specific profiling counters and performance metrics tailored to the respective GPU generation's microarchitecture", "Nsight Systems profiles only CPU-side code execution (Python overhead, data loading, preprocessing) while Nsight Compute profiles only GPU memory allocation and deallocation patterns, together covering the two main bottleneck categories but requiring separate runs to capture each, with no overlap in the metrics they collect", "Nsight Systems provides a system-level timeline view showing CPU activity, GPU kernel launches, memory transfers, and inter-device communication across the entire application. Nsight Compute provides detailed per-kernel analysis: occupancy, memory throughput, compute utilization, warp stall reasons, and roofline analysis. Use Nsight Systems first to identify bottleneck regions, then Nsight Compute to drill into specific slow kernels", "Nsight Compute is the newer version that replaces Nsight Systems entirely — it combines timeline profiling and per-kernel analysis into a single unified tool, and NVIDIA deprecated Nsight Systems starting with the CUDA 12 toolkit, making Nsight Compute the only supported profiling interface for Hopper-generation GPUs and beyond"],
      correct: 2,
      explanation: "The profiling workflow is: (1) Run Nsight Systems (`nsys profile python train.py`) to get the full timeline. Look for gaps between kernel launches (CPU overhead), unexpectedly slow kernels, or communication stalls. (2) Once you identify a specific kernel, use Nsight Compute (`ncu --set full python train.py --kernel-name regex:my_kernel`) to analyze it in detail: is it compute-bound or memory-bound? What is the occupancy? Are there bank conflicts in shared memory? What are the warp stall reasons? This two-level approach efficiently narrows down performance issues."
    },
    {
      type: "mc",
      question: "GPU occupancy measures the ratio of active warps to the maximum possible warps per SM. Why is 100% occupancy not always optimal, and what limits occupancy?",
      options: ["Occupancy is limited by three resources per SM: registers per thread, shared memory per block, and the maximum number of thread blocks. A kernel using many registers per thread can only run a few warps concurrently. However, fewer warps with more registers can outperform many warps with fewer registers, because register pressure causes spills to local memory (slow). The optimal occupancy balances latency hiding (more warps to cover memory stalls) against per-thread resource availability", "100% occupancy is always optimal because more active warps means more instruction-level parallelism available to the warp scheduler, and the GPU's hardware scheduler is designed to always benefit from additional warps. Lower occupancy universally degrades performance because it reduces the scheduler's ability to hide latency through warp interleaving, regardless of whether the kernel is compute-bound or memory-bound", "Occupancy is always 100% on modern GPUs (Ampere and later) because hardware-managed register spilling and dynamic shared memory allocation automatically balance resources across warps, ensuring maximum warp occupancy regardless of per-thread register usage. Manual occupancy tuning was necessary on older architectures (Volta and before) but is no longer relevant for modern ML workloads", "Occupancy only matters for graphics workloads that use the fixed-function rasterization pipeline, not for ML training which uses compute shaders and tensor cores. Tensor core operations bypass the standard warp scheduler entirely and operate on a dedicated execution pipeline where occupancy is determined by the matrix tile size rather than the number of active warps per SM"],
      correct: 0,
      explanation: "An A100 SM has 65,536 registers and supports up to 64 warps (2048 threads). A kernel using 128 registers per thread allows $65536 / (128 \\times 32) = 16$ warps per SM, giving 25% occupancy. Reducing to 64 registers allows 32 warps (50% occupancy) but may require spilling registers to local memory (~100x slower than register access). For compute-bound kernels (like matmul), fewer warps with full register usage often wins. For memory-bound kernels, more warps are needed to hide memory latency through warp switching. Shared memory limits work similarly: more shared memory per block means fewer blocks per SM."
    },
    {
      type: "mc",
      question: "Operator fusion in `torch.compile` or custom Triton kernels eliminates intermediate tensors. For a transformer block with LayerNorm, QKV projection, attention, output projection, another LayerNorm, and an MLP with SiLU gating, which operations are typically fused and which are not?",
      options: [
        "All operations in the transformer block — including the large matmuls, attention, LayerNorm, and activations — are fused into a single monolithic kernel that processes the entire block's computation in one launch, minimizing all kernel launch overhead and HBM accesses by keeping every intermediate tensor exclusively in SRAM throughout the full forward pass",
        "Large matrix multiplications (QKV projection, output projection, MLP up/down projections) are NOT fused with adjacent operations because they are compute-bound and already efficient as standalone cuBLAS calls. However, pointwise operations (LayerNorm, residual add, SiLU activation, dropout) ARE fused with each other and sometimes with the adjacent matmul epilogue, because these operations are memory-bound and fusion eliminates HBM round-trips between them",
        "Only the attention computation (softmax, masking, and the QK^T dot product) is fused into a single kernel via FlashAttention; all other operations including LayerNorm, residual connections, MLP projections, and activations run as separate kernels because their data dependencies prevent efficient fusion across the attention boundary",
        "Fusion is never applied during training because the backward pass requires access to individual intermediate activations for gradient computation — fusing operations would destroy the activation boundaries needed by autograd. Fusion is only applied during inference, where no backward pass is needed and intermediate activations can be safely discarded within the fused kernel"
      ],
      correct: 1,
      explanation: "The optimization strategy follows the roofline model. Matmuls have high arithmetic intensity and run near peak FLOP/s via cuBLAS — fusing a cheap elementwise op into them provides negligible benefit. But between matmuls, there are sequences of memory-bound ops: residual add + LayerNorm (read input, compute stats, normalize, write output), or SiLU activation + elementwise multiply in gated MLPs. Each unfused op reads from and writes to HBM. Fusing N consecutive pointwise ops reduces HBM accesses from 2N to 2 (one read, one write). `torch.compile`'s TorchInductor automatically identifies and fuses these pointwise chains."
    }
  ]
};
