// Assessment: Video & Beyond (E.4)
// Pure assessment — no info steps

export const videoAssessment = {
  id: "E.4-assess",
  sectionId: "E.4",
  title: "Assessment: Video & Beyond",
  difficulty: "hard",
  estimatedMinutes: 15,
  moduleType: "test",
  steps: [
    {
      type: "mc",
      question: "Temporal consistency is a central challenge in video generation. A diffusion model generates each frame conditioned on a text prompt, but without explicit temporal modeling, frames exhibit flickering and identity drift. What is the primary architectural approach to enforcing consistency?",
      options: ["Extending the 2D spatial attention with temporal attention layers that attend across frames at corresponding spatial positions, enforcing coherence of objects, lighting, and motion across time", "Limiting generation to very short clips under 0.5 seconds and stitching them together with learned transition networks, since temporal coherence degrades proportionally with clip duration", "Applying a post-processing neural network trained on optical flow estimation to warp each generated frame into alignment with its temporal neighbors, correcting flickering artifacts", "Generating each frame independently at very high spatial resolution so that the increased per-frame detail provides enough visual consistency cues for human perception to interpolate motion"],
      correct: 0,
      explanation: "Models like Video Diffusion Models, AnimateDiff, and Sora insert temporal attention blocks (or 3D convolutions) between the existing spatial attention layers. In temporal attention, a token at spatial position $(h, w)$ attends to tokens at the same position across all frames, learning that an object should maintain consistent appearance and that motion should be smooth. Some architectures use full 3D self-attention (each token attends across both space and time), trading higher compute for stronger consistency. The key insight: temporal coherence is not a post-processing problem but must be baked into the generation process."
    },
    {
      type: "mc",
      question: "A 10-second video at 24 FPS and $256 \\times 256$ resolution, tokenized with a spatial patch size of $16 \\times 16$ and temporal patch size of 1 (every frame), produces how many tokens?",
      options: ["$(256/16) \\times (256/16) \\times 24 = 256 \\times 24 = 6{,}144$ tokens, since only one frame per second requires spatial tokenization", "$(10 \\times 24) \\times (16 \\times 16) = 240 \\times 256 = 61{,}440$ tokens, since each patch contributes $16 \\times 16$ sub-tokens to the sequence", "$10 \\times 24 \\times 256 = 61{,}440$ tokens, where 256 is the raw pixel count per row and each row is treated as a single spatial token", "$(10 \\times 24) \\times (256/16)^2 = 240 \\times 256 = 61{,}440$ tokens, since each of the 240 frames contributes 256 spatial patch tokens"],
      correct: 3,
      explanation: "The calculation: 10 seconds $\\times$ 24 FPS = 240 frames. Each frame has $(256/16) \\times (256/16) = 16 \\times 16 = 256$ spatial patches. Total tokens: $240 \\times 256 = 61{,}440$. With self-attention at $O(n^2)$, this means $\\sim 3.8 \\times 10^9$ attention entries -- already straining memory at this modest resolution. At $1024 \\times 1024$ resolution, the same video would produce $240 \\times 4096 = 983{,}040$ tokens. This token explosion is the fundamental computational bottleneck of video generation."
    },
    {
      type: "mc",
      question: "Temporal patch size (the number of consecutive frames compressed into a single token) directly trades off temporal resolution against token count. Increasing temporal patch size from 1 to 4 (compressing 4 frames per token) reduces the token count by $4\\times$, but introduces what limitation?",
      options: ["The model can no longer generate coherent video sequences and instead produces independent images, because compressing multiple frames into one token destroys all inter-frame relationships", "Color accuracy and tonal consistency decrease proportionally with the compression ratio, since averaging across 4 frames blends different lighting conditions into a single muddied color representation", "It reduces the model's ability to represent fast motion and rapid scene changes -- events shorter than 4 frames are blurred within a single token's representation, and the model cannot generate frame-level variations within a temporal patch", "The spatial resolution within each frame is also reduced by $4\\times$ as a side effect, because the temporal and spatial dimensions share the same compression budget in the autoencoder's bottleneck layer"],
      correct: 2,
      explanation: "With a temporal patch size of 4 at 24 FPS, each token spans $4/24 \\approx 167$ ms. Any motion or change occurring within that window is compressed into a single latent vector. Fast hand gestures, eye blinks, or rapid scene transitions (~100ms events) get averaged or blurred. The model also cannot specify per-frame details within a temporal patch -- it generates a \"summary\" that the decoder must expand to 4 frames. This is directly analogous to spatial patching: larger patches reduce cost but lose fine detail."
    },
    {
      type: "mc",
      question: "Frame sampling strategies for video understanding (not generation) balance temporal coverage against token budget. Uniform sampling of $N$ frames from a long video fails when:",
      options: [
        "The video contains predominantly static scenes with minimal motion, where uniform sampling captures redundant near-identical frames that waste the token budget",
        "The video resolution exceeds the visual encoder's maximum supported input size, requiring spatial downsampling that destroys fine-grained details regardless of temporal sampling strategy",
        "Important events are brief relative to the video duration -- in a 5-minute video sampled to 16 frames, each frame represents ~19 seconds, so a 2-second key event may fall entirely between sampled frames and be invisible to the model",
        "The video contains more than one distinct scene with different backgrounds, causing the model to confuse object identities across the sampled frames from different scene contexts"
      ],
      correct: 2,
      explanation: "Uniform sampling assumes events are distributed evenly across the video. For a 5-minute video with 16 uniformly sampled frames, the sampling interval is ~19 seconds. A critical 2-second event (e.g., a decisive goal in a soccer match) has a roughly $2/19 \\approx 10\\%$ chance of being captured by any given frame. Adaptive strategies include: keyframe detection (sample more densely around motion/scene changes), hierarchical sampling (coarse pass to identify important segments, then fine sampling within them), or dynamic frame allocation based on query relevance."
    },
    {
      type: "mc",
      question: "Omni-modal models (e.g., GPT-4o, Gemini) aim to process and generate across text, image, audio, and video within a single model. What is the fundamental alignment challenge when integrating modalities that were pretrained separately?",
      options: ["Each modality's encoder was trained with different objectives (contrastive, reconstructive, predictive) and maps to embedding spaces with different geometric structures and semantic granularities, so forcing a shared space risks destroying modality-specific information", "The tokenizers for each modality must produce vocabularies of identical size so that the shared transformer allocates equal attention capacity per modality, and rebalancing vocabulary sizes across encoders requires prohibitively expensive retraining", "Omni-modal models inherently require more total training data than the sum of single-modality requirements, because cross-modal alignment creates an additional data need proportional to the product of all modality pairs", "Different modalities require fundamentally different GPU memory layouts and kernel configurations for efficient processing, making it impractical to co-locate vision, audio, and text encoders on shared accelerators"],
      correct: 0,
      explanation: "A CLIP vision encoder learns a space optimized for image-text retrieval (contrastive, normalized embeddings on a hypersphere). A speech encoder like HuBERT learns representations optimized for phonemic discrimination. A video encoder might use reconstruction objectives. These spaces have fundamentally different geometries: contrastive spaces are hyperspherical, reconstruction spaces may be approximately Gaussian, predictive spaces may have complex manifold structure. Naively projecting all into a shared space either requires the projections to be extremely expressive (adding parameters) or accepts lossy alignment. Successful omni-modal models typically use extensive joint training to co-adapt representations."
    },
    {
      type: "mc",
      question: "A 30-second video at 720p (1280$\\times$720), 30 FPS, with spatial patch size 16 and temporal patch size 2 produces tokens for an LLM backbone. Approximately how many visual tokens result, and how does this compare to a typical LLM context window?",
      options: ["~1,000,000 tokens (each pixel contributes roughly one token even after patching), requiring a completely new architectural paradigm beyond what current transformers can handle", "~2,000 tokens (aggressive spatial and temporal pooling reduces the representation to roughly 4--5 tokens per frame), fitting comfortably within any standard context window without compression", "~101,250 tokens (450 temporal slots $\\times$ 225 spatial tokens per frame pair), which exceeds the 32K--128K context windows of most LLMs, requiring either aggressive compression, sparse attention, or hierarchical processing", "~10,000 tokens (moderate spatial compression yields roughly 22 tokens per temporal slot), which is manageable with standard full self-attention and does not require specialized efficiency techniques"],
      correct: 2,
      explanation: "Frames: $30 \\times 30 = 900$. With temporal patch size 2: $900/2 = 450$ temporal slots. Spatial tokens per frame pair: $(1280/16) \\times (720/16) = 80 \\times 45 = 3600$. Total: $450 \\times 3600 = 1{,}620{,}000$ -- actually even larger than option C. Even with aggressive spatial compression to, say, 225 tokens (via a Perceiver or $4\\times$ spatial downsampling to 320$\\times$180 effective), you get $450 \\times 225 \\approx 101{,}250$ tokens. This far exceeds standard context windows, illustrating why video models must use aggressive spatial-temporal compression, memory-efficient attention, or streaming approaches."
    },
    {
      type: "mc",
      question: "Video generation models often use a cascaded approach: generate at low resolution (e.g., $64 \\times 64$), then apply spatial and temporal super-resolution models. Compared to directly generating at high resolution, what tradeoff does cascading introduce?",
      options: ["Each cascade stage can introduce its own artifacts -- spatial upsampling may hallucinate temporally inconsistent details, temporal interpolation may create ghosting, and errors accumulate across stages, but the approach is far more computationally tractable", "Cascading requires exactly 3 fixed stages (base, spatial upsampling, temporal interpolation) and deviating from this specific count causes training instability, since the noise schedules are jointly calibrated across all three stages", "Cascading always produces better results than direct generation with no downsides, since each stage is independently optimized on its specific subtask with specialized loss functions, architectures, and curated training data", "The low-resolution base model does not need temporal attention because at $64 \\times 64$ resolution, adjacent frames are similar enough that spatial self-attention alone captures inter-frame coherence without explicit temporal modeling"],
      correct: 0,
      explanation: "At $64 \\times 64$, the base model has a manageable $16$ spatial tokens per frame (with patch size 16) or $64$ tokens (patch size 8). Spatial super-resolution $64 \\to 256 \\to 1024$ adds details but must invent fine-grained textures that are consistent across frames. Temporal super-resolution (generating intermediate frames) must produce smooth motion but may create ghosting when objects move non-linearly between keyframes. Each stage is independently trained and may have different error modes. Despite these challenges, cascading is the dominant approach because direct $1024 \\times 1024 \\times 30\\text{fps}$ generation remains prohibitively expensive."
    },
    {
      type: "mc",
      question: "Modality-specific tokenization rates vary enormously. Text produces ~1 token per word, images produce ~256-1024 tokens, and audio at 24kHz with Encodec produces ~75 tokens/second across multiple RVQ levels. For a unified autoregressive model processing a 30-second video with audio, this asymmetry creates what problem?",
      options: [
        "The shared vocabulary runs out of codebook space because video, audio, and text tokens must all share a single discrete vocabulary, and the combined modality requirements exceed practical codebook sizes by orders of magnitude",
        "The audio and video token streams overwhelm the text tokens -- a 30-second clip produces ~150K+ video tokens and ~2250+ audio tokens but only ~50 text tokens for a caption, so the model's capacity and context window are dominated by dense perceptual modalities",
        "Text tokens become disproportionately influential in the attention mechanism because their lower frequency gives each text token more semantic density per position, causing the model to systematically over-weight textual reasoning over perceptual inputs",
        "The model fundamentally cannot process more than one modality at a time within a single forward pass, requiring separate sequential passes for each modality with an explicit learned fusion step between them"
      ],
      correct: 1,
      explanation: "The token rate asymmetry is extreme: video can produce 5000+ tokens/second, audio 75+ tokens/second, but text ~2-3 tokens/second of speech. In a unified sequence, the model's attention is dominated by perceptual tokens. This has several consequences: (1) the context window fills up with vision/audio before meaningful text can be included, (2) compute is spent mostly on perceptual self-attention, (3) the model may learn to \"ignore\" the sparse text tokens. Solutions include aggressive perceptual compression (Perceiver, Q-Former), modality-specific encoders that run outside the main transformer, or hierarchical architectures that process modalities at different rates."
    },
    {
      type: "mc",
      question: "Sora (OpenAI) generates videos using a diffusion transformer (DiT) operating on spacetime patches. The use of a transformer (rather than U-Net) architecture for video diffusion offers which key advantage?",
      options: ["Transformers are always computationally faster than U-Nets for diffusion because self-attention avoids the redundant multi-scale feature maps inherent in encoder-decoder structures, reducing total FLOPs proportionally to the number of resolution stages", "Transformer-based diffusion eliminates the need for a noise schedule entirely, since self-attention implicitly learns the optimal denoising trajectory from data without requiring a predefined variance schedule or timestep conditioning signal", "U-Nets cannot process video data at any resolution because their fixed spatial downsampling and upsampling structure fundamentally does not accommodate the temporal dimension, preventing any extension to sequential frame generation", "Transformers treat spatial and temporal dimensions uniformly as token sequences, enabling flexible attention patterns (spatial-only, temporal-only, or full spacetime), seamless scaling via standard transformer scaling laws, and natural handling of variable resolutions"],
      correct: 3,
      explanation: "U-Nets have a fixed hierarchical structure with hard-coded spatial downsampling/upsampling stages. Adapting them for video requires inserting temporal layers at each scale, creating architectural complexity. DiTs flatten everything into a 1D sequence of spacetime patch tokens, then apply standard transformer blocks. This offers: (1) uniform treatment of space and time -- attention can be spatial, temporal, or full 3D based on compute budget; (2) known scaling laws from LLMs transfer to guide capacity planning; (3) variable-length sequences handle different resolutions and durations naturally; (4) infrastructure optimizations (FlashAttention, tensor parallelism) apply directly."
    },
    {
      type: "mc",
      question: "A researcher wants to build a model that understands and generates across text, images, audio, and video. They consider two architectures: (A) separate specialized encoders/decoders per modality connected via a shared latent space, vs. (B) a single tokenizer that maps all modalities to a shared discrete vocabulary and a single autoregressive transformer. What is the core tradeoff?",
      options: ["Architecture B is always superior because a unified model is simpler to train end-to-end, avoids integration complexity of separate encoders, and benefits from positive transfer between modalities that consistently outweighs capacity competition or tokenization mismatches", "Architecture A preserves modality-specific representations and allows independent optimization, but requires complex routing and loses emergent cross-modal reasoning; Architecture B enables cross-modal in-context learning but suffers from tokenization-rate mismatches and shared capacity limits", "Architecture A is always superior because independently optimized specialized components consistently outperform general-purpose ones, and the modular design lets each encoder use the ideal architecture for its modality without compromise from shared parameters", "There is no meaningful tradeoff between the two approaches -- given sufficient training data and compute, both converge to identical capabilities, making the choice purely a matter of engineering convenience and team-specific implementation preferences"],
      correct: 1,
      explanation: "This is one of the defining architectural debates in multimodal AI. Architecture A (modular, e.g., Flamingo, LLaVA) benefits from plug-and-play components: upgrade the vision encoder without retraining the LLM. But the integration points (projection layers, cross-attention) may be information bottlenecks. Architecture B (monolithic, e.g., Chameleon, Gemini-style) treats everything as tokens in one sequence, potentially enabling emergent behaviors like \"reasoning about what an image would sound like.\" But it faces tokenization-rate mismatches (video dominates the sequence), codebook design challenges (one vocabulary for all modalities?), and requires enormous training data covering all modality combinations. Current frontier models increasingly lean toward hybrid approaches."
    }
  ]
};

